<a href="https://colab.research.google.com/github/reis-47/Exercicios_ComputacaoGrafico/blob/main/Exercicios3_0224.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import matplotlib.pyplot as plt
import numpy as np
import math

#variaveis
matriz_a = np.array([[1, 3, 2], [4, 7, 6],])
print(matriz_a)

matriz_b= np.array([[2, 8], [3, 1], [5, 9]])
print(matriz_b)

numero_linha = 0
numero_coluna = 0

#if matriz_a.shape[0] == matriz_b.shape[1]:
#    print("As matrizes podem ser multiplicadas.")
#else:
#    print("As matrizes não podem ser multiplicadas.")

matriz_a_linha, matriz_a_coluna = matriz_a.shape #na funcao np.shape: 0 vale o numero de linhas, 1 o numero de colunas
matriz_b_linha, matriz_b_coluna = matriz_b.shape

if matriz_a_coluna != matriz_b_linha:
  print("As matrizes não podem ser multiplicadas.")
else:
  print("As matrizes podem ser multiplicadas.")
  resultado = np.zeros((matriz_a_linha, matriz_b_coluna))

  for numero_linha in range (matriz_a_linha):
    for numero_coluna in range (matriz_b_coluna):
      soma = 0
      for k in range (matriz_a_coluna):
        soma += matriz_a[numero_linha, k] * matriz_b[k, numero_coluna]
      resultado[numero_linha, numero_coluna] = soma

print(resultado)


[[1 3 2]
 [4 7 6]]
[[2 8]
 [3 1]
 [5 9]]
As matrizes podem ser multiplicadas.
[[21. 29.]
 [59. 93.]]


In [98]:
import matplotlib.pyplot as plt
import numpy as np
import math

#variaveis
matriz_diagonal = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 7]])
print(matriz_diagonal)

#conferir se eh diagonal
matriz_diagonal_linha, matriz_diagonal_coluna = matriz_diagonal.shape

if matriz_diagonal_linha != matriz_diagonal_coluna:
  print("A matriz não eh quadrada, linhas e colunas iguais. \n")
else:
  print("A matriz eh quadrada, linhas e colunas iguais. \n")

  i = matriz_diagonal_linha
  j = matriz_diagonal_coluna

  if i != j and matriz_diagonal_linha[i][j] != 0:
    print("A matriz não eh diagonal. \n")
  else:
    print("A matriz eh diagonal. \n")

[[2 0 0]
 [0 1 0]
 [0 0 7]]
A matriz eh quadrada, linhas e colunas iguais. 

A matriz eh diagonal. 



In [99]:
import matplotlib.pyplot as plt
import numpy as np
import math

#variaveis
matriz_identidade = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) #pra criar uma matriz 3X3 precisa usar colchetes duplos [[numeros], [numeros], [numeros]]
print(matriz_identidade)

#conferir se eh uma diagonal
matriz_identidade_linha, matriz_identidade_coluna = matriz_identidade.shape

if matriz_identidade_linha != matriz_identidade_coluna:
  print("<n A matriz não eh quadrada, linhas e colunas iguais. \n")
else:
  print("A matriz eh quadrada, linhas e colunas iguais. \n")

  #conferir se ela eh identidade
  i_identidade = matriz_identidade_linha
  j_identidade = matriz_identidade_coluna
  k = 0
  confirmar_identidade = 1

  for i_identidade in range (matriz_identidade_linha):
    for j_identidade in range (matriz_identidade_coluna):
      for k in range (matriz_identidade_coluna):
        if (i_identidade == k and matriz_identidade[i_identidade][k] != 1) or (i_identidade != k and matriz_identidade[i_identidade][k] != 0):
          confirmar_identidade = 0

  if confirmar_identidade == 1:
    print("A matriz eh identidade. \n")
  elif confirmar_identidade == 0:
    print("A matriz não eh identidade. \n")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
A matriz eh quadrada, linhas e colunas iguais. 

A matriz eh identidade. 



In [100]:
import matplotlib.pyplot as plt
import numpy as np
import math

#variaveis
matriz_transposta_original = np.array([[2, 3, 8], [6, 0, 4], [1, 5, 7]])
matriz_transposta = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(matriz_transposta_original)

matriz_transposta_original_linha, matriz_transposta_original_coluna = matriz_transposta_original.shape

i_transposta = matriz_transposta_original_linha
j_transposta = matriz_transposta_original_coluna

for i_transposta in range (matriz_transposta_original_linha):
  for j_transposta in range (matriz_transposta_original_coluna):
    matriz_transposta[j_transposta][i_transposta] = matriz_transposta_original[i_transposta][j_transposta]

print(matriz_transposta)

[[2 3 8]
 [6 0 4]
 [1 5 7]]
[[2 6 1]
 [3 0 5]
 [8 4 7]]


In [102]:
import matplotlib.pyplot as plt
import numpy as np
import math

#variaveis
matriz_escalar_original = np.array([[2, 3, 8], [6, 0, 4], [1, 5, 7]])
matriz_escalar = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(matriz_escalar_original)

escalar = 3

matriz_escalar_original_linha, matriz_escalar_original_coluna = matriz_escalar_original.shape

i_escalar = matriz_escalar_original_linha
j_escalar = matriz_escalar_original_coluna

for i_escalar in range (matriz_escalar_original_linha):
  for j_escalar in range (matriz_escalar_original_coluna):
    matriz_escalar[i_escalar][j_escalar] = matriz_escalar_original[i_escalar][j_escalar] * escalar

print(matriz_escalar)

[[2 3 8]
 [6 0 4]
 [1 5 7]]
[[ 6  9 24]
 [18  0 12]
 [ 3 15 21]]
